[build]
command = "npm run build"
publish = ".next/standalone"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next/static"
entry-point = ".next/standalone"

[env.production]
name = "venchill-production"
route = "venchill.pages.dev/*"

[env.staging]
name = "venchill-staging"
route = "staging.venchill.pages.dev/*"
